services:
  - type: web
    name: hr-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: REPORT_TO_EMAIL
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
